FROM    python:slim
COPY    /api/ /var/www/tests
WORKDIR /var/www/tests
RUN     pip install --upgrade pip
RUN     pip install -r requirements.txt
CMD ["python", "-m", "pytest", "--reruns=0", "--html=test_report/api_report.html", "--self-contained-html", "--color=yes" , "-v", "--tb=short"]
