version: '3.7'

services:
  selenoid:
    container_name: selenoid1
    image: "aerokube/selenoid"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "./browsers.json:/etc/selenoid/browsers.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD.:/etc/selenoid"
    command: ["-conf", "/etc/selenoid/browsers.json", "-limit", "5", "-session-delete-timeout", "20s", "-timeout", "30s"]

  selenoid-ui:
    container_name: selenoid-ui1
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8081:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

  ui_tests:
    container_name: test
    network_mode: bridge
    links:
      - selenoid
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - selenoid
      - selenoid-ui
    volumes:
      - "./test_report/:/var/www/tests/test_report/"
